---
- name: APACHE2 INSTALLATION AND USER MANAGEMENT
  become: yes
  hosts: webhost
  gather_facts: no

  vars_prompt:
  - name: keyword
    prompt: Which word you want to display?

  #vars: 
  #  src_path: /home/ansiblevm
  #  dest_path: /var/www/html
  roles:
  - user
  - apache

    #tasks:
    #- name: Install apache2 and start 
    #apt: pkg=apache2 state=present

    #- name: Copy html template
    #template: src={{src_path}}/index.html.j2 dest={{dest_path}}/index.html
    #notify: Restart apache2 server

    #- name: Start apache2 server
    #service: name=apache2 state=started enabled=yes
    
    #- name: create/delete a user
    #user: name={{ item }}  state=absent
    #with_items: 
    #  - webhost_username
    #  - all_username
    #  - web1_username

        #handlers:
        #- name: Restart apache2 server
        #service: name=apache2 state=restarted



